<?php global $router;
//TODO: Hacer routing configurable
if (isset($routing['entityGroupSlug'])) {
	$routerNew = 'backoffice_new_group';
	$routerEdit = 'backoffice_edit_group';
	$routerDelete = 'backoffice_delete_group';
} else {
	$routerNew = 'backoffice_new';
	$routerEdit = 'backoffice_edit';
	$routerDelete = 'backoffice_delete';
}

?>
<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-th"></i> <?php echo $title; ?></h2>
					</div>
					<div class="box-content">
						<a class="btn btn-success pull-right" href="<?php echo $router->generate($routerNew, $routing); ?>">
							<i class="icon-plus icon-white"></i>  Nuevo                                            
						</a>
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
							  	  <?php foreach ($fields as $field) {
							  	  if ($field->layoutFieldMaster !== null) { ?>
								  	<th><?php echo $field->title; ?></th>
								  <?php }
								  } ?>
								  <th>Acciones</th>
							  </tr>
						  </thead>   
						  <?php if (!empty($data)) { ?>
						  <tbody>
						  	<?php foreach($data as $row) { 
						  		$routing['entity'] = $row->$PKField;
						  	?>
							<tr>
								<?php foreach ($fields as $field) {
									if ($field->layoutFieldMaster !== null) {
										$fieldName = $field->name;
										$params = array(
											'display' => $field->getDisplay($row->$fieldName));
										$field->layoutFieldMaster->view($controller, $templateName, $params);
									}
								} ?>
								<td class="center">
									<a class="btn btn-info" href="<?php echo $router->generate($routerEdit, $routing); ?>">
										<i class="icon-edit icon-white"></i>  
										Editar                                            
									</a>
									<button class="btn btn-danger btnDelete" value="<?php echo $router->generate($routerDelete, $routing); ?>">
										<i class="icon-trash icon-white"></i> 
										Eliminar
									</button>
								</td>
							</tr>
							<?php } ?>
						  </tbody>
						  <?php } ?>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->

			<div class="modal hide fade" id="modalDelete" style="display: block;">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h3>Eliminar elemento</h3>
				</div>
				<div class="modal-body">
					<p>¿Estás seguro de que deseas eliminr este elemento?</p>
				</div>
				<div class="modal-footer">
					<a href="#" class="btn" data-dismiss="modal">Cancelar</a>
					<a href="#" class="btn btn-danger"><i class="icon-trash icon-white"></i> Eliminar</a>
				</div>
			</div>