<div class="control-group<?php if (isset($controlClass)) { echo ' '.$controlClass; } ?>">
								<label class="control-label" for="<?php echo $id; ?>"><?php echo $title; ?></label>
								<div class="controls">
								  <label class="checkbox">
									<input type="checkbox" id="<?php echo $id; ?>" name="<?php echo $name; ?>" value="1" <?php if ($value==1) { ?> checked="checked"<?php } ?>>
									<?php if (isset($description)) { ?><span class="help-inline"><?php echo $description; ?></span><?php } ?>
									<?php if (isset($help)) { ?><span class="help-inline"><?php echo $help; ?></span><?php } ?>
								  </label>
								</div>
							  </div>