<?php global $router; ?>
<div class="row-fluid">
				<div class="box span12">
					<div class="box-header well">
						<h2><i class="icon-home"></i> Inicio</h2>
					</div>
					<div class="box-content">
						<h1>Rox Office <small>OOP, MVC, Systems friendly, ligero, escalable, reutilizable, configurable por XML</small></h1>
						<p>Es un CMF (Content Management Framework) basado en <strong>Rox Framework</strong>, un framework PHP diseñado para realizar proyectos corporativos ligeros y altamente configurables, específicamente pensado para la reutilización de código y facilidad de implementación y mantenimiento para el departamento de sistemas</p>
						<p>Algunas de sus características son:</p>
						<ul>
							<li>100% configurable mediante XML</li>
							<li>Todas las clases de Rox Office pueden ser heredadas y sustituídas por las tuyas propias para no perder nunca el control de la web</li>
							<li>Tu modelo de datos no debe adaptarse al backoffice: Rox Office se adapta a ti</li>
							<li>Independiente de sistemas de login: restringe el acceso a la web a nivel de sistema o prográmalo desde tu controlador</li>
							<li>Genera fácilmente distintas oficinas para cada perfil de usuario</li>
							<li>Utiliza el archivo de routing general de tu aplicación para controlar el nombre de las URLs</li>
							<li>Configura tus plantillas Maestro y Detalle genéricas</li>
							<li>Crea plantillas Maestro y Detalle específicas para entidades concretas</li>
							<li>Desarrolla fácilmente tus propios templates</li>
						</ul>
						<p>El template de este backoffice está basado en <strong><a href="http://usman.it/free-responsive-admin-template/">Charisma</a></strong>, por <strong><a href="http://usman.it">Muhammad Usman</a></strong>, pero puede ser sustituído desde el archivo de configuración <em>"/conf/RoxOffice/rox-office-cms.xml"</em>.</p>
						<p><strong>Puedes modificar esta página de inicio por la que más se adecúe a tu proyecto sustituyendo el archivo <em>"/app/view/RoxOffice/Charisma/home.phtml"</em>.</strong></p>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>