<?php global $router; ?>
<!DOCTYPE html>
<html lang="es">
<head>
	<!--
		Charisma v1.0.0

		Copyright 2012 Muhammad Usman
		Licensed under the Apache License v2.0
		http://www.apache.org/licenses/LICENSE-2.0

		http://usman.it
		http://twitter.com/halalit_usman
	-->
	<meta charset="utf-8">
	<title><?php if (isset($entityTitle)) { echo $entityTitle; ?> | <?php } ?>Backoffice | Vodafone Basket</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- The styles -->
	<link id="bs-css" href="/css/Charisma/bootstrap-spacelab.css" rel="stylesheet">
	<style type="text/css">
		body {
			padding-bottom: 40px;
		}
		.sidebar-nav {
			padding: 9px 0;
		}
		.navbar .brand {
			padding: 2px 20px 0;
	  	}
	</style>
	<link href="/css/Charisma/bootstrap-responsive.css" rel="stylesheet">
	<link href="/css/Charisma/charisma-app.css" rel="stylesheet">
	<link href="/css/Charisma/jquery-ui-1.8.21.custom.css" rel="stylesheet">
	<link href='/css/Charisma/fullcalendar.css' rel='stylesheet'>
	<link href='/css/Charisma/fullcalendar.print.css' rel='stylesheet'  media='print'>
	<link href='/css/Charisma/chosen.css' rel='stylesheet'>
	<link href='/css/Charisma/uniform.default.css' rel='stylesheet'>
	<link href='/css/Charisma/colorbox.css' rel='stylesheet'>
	<link href='/css/Charisma/jquery.cleditor.css' rel='stylesheet'>
	<link href='/css/Charisma/jquery.noty.css' rel='stylesheet'>
	<link href='/css/Charisma/noty_theme_default.css' rel='stylesheet'>
	<link href='/css/Charisma/elfinder.min.css' rel='stylesheet'>
	<link href='/css/Charisma/elfinder.theme.css' rel='stylesheet'>
	<link href='/css/Charisma/jquery.iphone.toggle.css' rel='stylesheet'>
	<link href='/css/Charisma/opa-icons.css' rel='stylesheet'>
	<link href='/css/Charisma/uploadify.css' rel='stylesheet'>

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- The fav icon -->
	<link rel="shortcut icon" href="/favicon.png">
		
</head>

<body>
	<!-- topbar starts -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="/oficina/"> <img alt="Charisma Logo" src="/img/logo_bitoon.png" /> </a>
				<ul class="nav">
					<li><a href="/">Visitar sitio</a></li>
				</ul>
				<!-- theme selector starts -->
				<div class="btn-group pull-right theme-container" >
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-tint"></i><span class="hidden-phone"> Cambiar tema </span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu" id="themes">
						<li><a data-value="classic" href="#"><i class="icon-blank"></i> Classic</a></li>
						<li><a data-value="cerulean" href="#"><i class="icon-blank"></i> Cerulean</a></li>
						<li><a data-value="cyborg" href="#"><i class="icon-blank"></i> Cyborg</a></li>
						<li><a data-value="redy" href="#"><i class="icon-blank"></i> Redy</a></li>
						<li><a data-value="journal" href="#"><i class="icon-blank"></i> Journal</a></li>
						<li><a data-value="simplex" href="#"><i class="icon-blank"></i> Simplex</a></li>
						<li><a data-value="slate" href="#"><i class="icon-blank"></i> Slate</a></li>
						<li><a data-value="spacelab" href="#"><i class="icon-blank"></i> Spacelab</a></li>
						<li><a data-value="united" href="#"><i class="icon-blank"></i> United</a></li>
					</ul>
				</div>
				<!-- theme selector ends -->
				
				<!-- user dropdown starts -->
				<!--
				<div class="btn-group pull-right" >
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-user"></i><span class="hidden-phone"> admin</span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">Profile</a></li>
						<li class="divider"></li>
						<li><a href="login.html">Logout</a></li>
					</ul>
				</div> -->
				<!-- user dropdown ends -->
				<!--
				<div class="top-nav nav-collapse">
					<ul class="nav">
						<li><a href="#">Visit Site</a></li>
						<li>
							<form class="navbar-search pull-left">
								<input placeholder="Search" class="search-query span2" name="query" type="text">
							</form>
						</li>
					</ul>
				</div>--><!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<!-- topbar ends -->
	<div class="container-fluid">
		<div class="row-fluid">
				
			<!-- left menu starts -->
			<div class="span2 main-menu-span">
				<div class="well nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li><a class="ajax-link" href="/oficina/"><i class="icon-home"></i><span class="hidden-tablet"> Inicio</span></a></li>
						<?php foreach ($entities as $entityName=>$entity) {
							if ($entity instanceof RoxOffice\Controllers\Rox_EntityManager) { ?>
						<li><a class="ajax-link" href="<?php echo $router->generate('backoffice_master', array('entitySlug'=>$entityName)); ?>"><i class="icon-th"></i><span class="hidden-tablet"> <?php echo $entity->title; ?></span></a></li>
							<?php } else { ?>
						<li class="nav-header hidden-tablet"><?php echo $entity['title']; ?></li>
							<?php foreach ($entity['entities'] as $entityGroupedName=>$entityGrouped) { ?>
						<li><a class="ajax-link" href="<?php echo $router->generate('backoffice_master_group', array('entityGroupSlug'=>$entityName, 'entitySlug'=>$entityGroupedName)); ?>"><i class="icon-th"></i><span class="hidden-tablet"> <?php echo $entityGrouped->title; ?></span></a></li>
							<?php }
							}
						} ?>
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
			<!-- left menu ends -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">¡Aviso!</h4>
					<p>Necesitas tener <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> habilitado para poder utilizar este sitio.</p>
				</div>
			</noscript>
			
			<div id="content" class="span10">
			<!-- content starts -->
			<div>
				<ul class="breadcrumb">
					<?php $started=false; foreach ($breadcrumb as $name=>$url) { ?>
					<li>
						 <?php if ($started) { ?><span class="divider">/</span> <?php } ?><a href="<?php echo $url ?>"><?php echo $name; ?></a>
					</li>
					<?php $started=true; } ?>
				</ul>
			</div>

    		<?php if (isset($contentLayout)) { $contentLayout->view($controller, $templateName, $contentParams); } ?>

			<!-- content ends -->
			</div><!--/#content.span10-->
		</div><!--/fluid-row-->
				
		<hr>
		<!--
		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>
		-->
		<!-- <footer>
			<p class="pull-left">&copy; <a href="http://usman.it" target="_blank">Miguel López</a> 2014</p>
			<p class="pull-right">Powered by: <a href="http://usman.it/free-responsive-admin-template">Charisma</a></p>
		</footer> -->
		
	</div><!--/.fluid-container-->

	<!-- external javascript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->

	<!-- jQuery -->
	<script src="/js/Charisma/jquery-1.7.2.min.js"></script>
	<!-- jQuery UI -->
	<script src="/js/Charisma/jquery-ui-1.8.21.custom.min.js"></script>
	<!-- transition / effect library -->
	<script src="/js/Charisma/bootstrap-transition.js"></script>
	<!-- alert enhancer library -->
	<script src="/js/Charisma/bootstrap-alert.js"></script>
	<!-- modal / dialog library -->
	<script src="/js/Charisma/bootstrap-modal.js"></script>
	<!-- custom dropdown library -->
	<script src="/js/Charisma/bootstrap-dropdown.js"></script>
	<!-- scrolspy library -->
	<script src="/js/Charisma/bootstrap-scrollspy.js"></script>
	<!-- library for creating tabs -->
	<script src="/js/Charisma/bootstrap-tab.js"></script>
	<!-- library for advanced tooltip -->
	<script src="/js/Charisma/bootstrap-tooltip.js"></script>
	<!-- popover effect library -->
	<script src="/js/Charisma/bootstrap-popover.js"></script>
	<!-- button enhancer library -->
	<script src="/js/Charisma/bootstrap-button.js"></script>
	<!-- accordion library (optional, not used in demo) -->
	<script src="/js/Charisma/bootstrap-collapse.js"></script>
	<!-- carousel slideshow library (optional, not used in demo) -->
	<script src="/js/Charisma/bootstrap-carousel.js"></script>
	<!-- autocomplete library -->
	<script src="/js/Charisma/bootstrap-typeahead.js"></script>
	<!-- tour library -->
	<script src="/js/Charisma/bootstrap-tour.js"></script>
	<!-- library for cookie management -->
	<script src="/js/Charisma/jquery.cookie.js"></script>
	<!-- calander plugin -->
	<script src='/js/Charisma/fullcalendar.min.js'></script>
	<!-- data table plugin -->
	<script src='/js/Charisma/jquery.dataTables.min.js'></script>

	<!-- chart libraries start -->
	<script src="/js/Charisma/excanvas.js"></script>
	<script src="/js/Charisma/jquery.flot.min.js"></script>
	<script src="/js/Charisma/jquery.flot.pie.min.js"></script>
	<script src="/js/Charisma/jquery.flot.stack.js"></script>
	<script src="/js/Charisma/jquery.flot.resize.min.js"></script>
	<!-- chart libraries end -->

	<!-- select or dropdown enhancer -->
	<script src="/js/Charisma/jquery.chosen.min.js"></script>
	<!-- checkbox, radio, and file input styler -->
	<script src="/js/Charisma/jquery.uniform.min.js"></script>
	<!-- plugin for gallery image view -->
	<script src="/js/Charisma/jquery.colorbox.min.js"></script>
	<!-- rich text editor library -->
	<script src="/js/Charisma/jquery.cleditor.min.js"></script>
	<!-- notification plugin -->
	<script src="/js/Charisma/jquery.noty.js"></script>
	<!-- file manager library -->
	<script src="/js/Charisma/jquery.elfinder.min.js"></script>
	<!-- star rating plugin -->
	<script src="/js/Charisma/jquery.raty.min.js"></script>
	<!-- for iOS style toggle switch -->
	<script src="/js/Charisma/jquery.iphone.toggle.js"></script>
	<!-- autogrowing textarea plugin -->
	<script src="/js/Charisma/jquery.autogrow-textarea.js"></script>
	<!-- multiple file upload plugin -->
	<script src="/js/Charisma/jquery.uploadify-3.1.min.js"></script>
	<!-- history.js for cross-browser state change on ajax -->
	<script src="/js/Charisma/jquery.history.js"></script>
	<!-- application script for Charisma demo -->
	<script src="/js/Charisma/charisma.js"></script>
	
		
</body>
</html>
